name: PR Checks

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Vulnerability Scan
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...

      - name: Test
        run: go test -v ./...
